# Generated by Django 3.2.4 on 2021-06-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='friend',
            field=models.ManyToManyField(to='movieApp.Friend'),
        ),
    ]
