# Generated by Django 3.2.4 on 2021-06-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_auto_20210610_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='friend',
            field=models.ManyToManyField(related_name='movie', to='movieApp.Friend'),
        ),
    ]
